import SideNav from "@/components/SideNav";
import {Metadata} from "next";

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function DashBoardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="container mx-auto w-full px-4">
			<div className="pt-4 flex flex-col items-center w-full">
				<SideNav />
			</div>
			{children}
		</div>
	);
}
