import Header from "@/components/Header";
import {Toaster} from "@/components/ui/toaster";
import {Metadata} from "next";

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function DashBoardLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="container mx-auto w-full px-4">
			<>
				<Header />
				{children}
				<Toaster />
			</>
		</div>
	);
}
